site_name: Robodyno 文档
nav:
  - 开始:
    - index.md
    - 安装: start/installation.md
    - 快速开始: start/quickstart.md
  - 深入了解:
    - deep-dive/index.md
    - 接口: 
      - CAN 总线: deep-dive/interfaces/can-bus.md
      - Webots: deep-dive/interfaces/webots.md
    - 组件: 
      - deep-dive/components/index.md
      - 伺服减速电机: deep-dive/components/motor.md
      - 直线运动模组: deep-dive/components/slider-module.md
      - PWM 扩展模块: deep-dive/components/pwm-driver.md
      - 步进电机驱动模块: deep-dive/components/stepper-driver.md
      - IMU 传感器: deep-dive/components/imu-sensor.md
    - 电机运动模式: deep-dive/motor-modes.md
  - Robodyno CLI:
    - commands/index.md
    - list: commands/list.md
    - monitor: commands/monitor.md
    - motor: 
      - commands/motor/index.md
      - info: commands/motor/info.md
      - enable: commands/motor/enable.md
      - disable: commands/motor/disable.md
      - init: commands/motor/init.md
      - pos: commands/motor/pos.md
      - vel: commands/motor/vel.md
      - torque: commands/motor/torque.md
      - config: commands/motor/config.md
      - calibrate: commands/motor/calibrate.md
      - clear-errors: commands/motor/clear-errors.md
      - reboot: commands/motor/reboot.md
      - estop: commands/motor/estop.md
      - reset: commands/motor/reset.md
  - Robodyno API: 
    - references/index.md
    - robodyno.interfaces:
      - CanBus: references/interfaces/can_bus.md
      - Webots: references/interfaces/webots.md
    - robodyno.components:
      - can_bus:
        - references/can_bus/index.md
        - Motor: references/can_bus/motor.md
        - SliderModule: references/can_bus/slider_module.md
        - PwmDriver: references/can_bus/pwm_driver.md
        - StepperDriver: references/can_bus/stepper_driver.md
        - ImuSensor: references/can_bus/imu_sensor.md
      - webots:
        - references/webots/index.md
        - Motor: references/webots/motor.md
        - SliderModule: references/webots/slider_module.md
  - 常见问题解答: faq.md
  - 贡献: contributing.md
  - 免责声明: disclaimer.md
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - navigation.sections
    - content.code.copy
extra_css:
  - stylesheets/custom.css
plugins:
  - mike
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            heading_level: 2
            members_order: source
            group_by_category: false
          paths: [src]
  - search:
      separator: '[\s\u200b\-]'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.tabbed:
      alternate_style: true 

copyright: Copyright &copy; 2007 - 2023 RobotTime

extra:
  generator: false
  version:
    provider: mike